### PR TITLE
Grouping checks in rulesets

### PR DESCRIPTION
**Pull request by lachmanfrantisek**
- Use checks grouping in fedora rulese.
- Add support for grouping checks in ruleset.

-----

### TODO

- [x] tests

### CODE REVIEW

**Comment by TomasTomecek** [comment]
Thinking out loud: would it be better to name it `check-names`?

**Comment by lachmanfrantisek** [comment]
> Thinking out loud: would it be better to name it check-names?

I'm not sure. I like `name`+`names` or `check_name`+`check_names`.

**Comment by TomasTomecek** [comment]
okay, let's leave it as is

**Comment by lachmanfrantisek** [comment]
@TomasTomecek I think I am ready for the review.

**Pull request merged**
