### PR TITLE
Make the location of ruleset more generic

### PR DESCRIPTION
**Pull request by lachmanfrantisek**
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=2036710
Fixes: #260
Signed-off-by: Frantisek Lachman <flachman@redhat.com>

### CODE REVIEW

**Comment by lachmanfrantisek** [comment]
Manually tested from the PR build done by packit:
```
[root@d909ad459e4f /]# dnf install -y dnf-plugins-core
[root@d909ad459e4f /]# dnf copr enable packit/user-cont-colin-285
[root@d909ad459e4f /]# dnf install -y colin-doc-0.5.0-1.20220107104400289317.pr285.26.gd195a1f.fc36.noarch colin-0.5.0-1.20220107104400289317.pr285.26.gd195a1f.fc36.noarch python3-colin-0.5.0-1.20220107104400289317.pr285.26.gd195a1f.fc36.noarch
[root@d909ad459e4f /]# colin --version
colin, version 0.5.0
[root@d909ad459e4f /]# colin list-rulesets
default (/usr/share/colin/rulesets/default.json)
fedora  (/usr/share/colin/rulesets/fedora.json)
[root@d909ad459e4f /]# colin list-checks
maintainer_label
   -> Label 'maintainer' has to be specified.
   -> The name and email of the maintainer (usually the submitter).
   -> https://fedoraproject.org/wiki/Container:Guidelines#LABELS
   -> label, maintainer, required

from_tag_not_latest
   -> In FROM, tag has to be specified and not 'latest'.
   -> Using the 'latest' tag may cause unpredictable builds.It is recommended that a specific tag is used in the FROM.
   -> https://fedoraproject.org/wiki/Container:Guidelines#FROM
   -> dockerfile, from, baseimage, latest, required

maintainer_deprecated
   -> Dockerfile instruction `MAINTAINER` is deprecated.
   -> Replace with label 'maintainer'.
   -> https://docs.docker.com/engine/reference/builder/#maintainer-deprecated
   -> dockerfile, maintainer, deprecated, required
```

**Comment by lachmanfrantisek** [comment]
Finally, also [TF results](http://artifacts.dev.testing-farm.io/14a6d996-15a4-41db-a383-062624d06572/) show the correct output -- I've changed the directory so we are sure we don't load rulesets from the local directory.

**Review by jpopelka — APPROVED** [review]
Looks OK

**Review by TomasTomecek — APPROVED** [review]
nice and easy fix, LGTM

**Pull request merged**
