### PR TITLE
Add support for the python2

### PR DESCRIPTION
**Pull request by lachmanfrantisek**
- Implement loader for the python2.
- Correct super calls to be compatible.
- Add more versions of the python to `setup.py`.

### CODE REVIEW

**Comment by TomasTomecek** [comment]
Works fine with py3, fails with py2 (tested from git):
```
$ PYTHONPATH=/home/tt/g/conu python2 -m colin.cli.colin check --debug -f ./rulesets/redhat.json ~/g/postgresql-container/9.6/Dockerfile.fedora
09:39:38.551 colin.py          DEBUG  Checking started.
09:39:38.551 target.py         DEBUG  Finding target '/home/tt/g/postgresql-container/9.6/Dockerfile.fedora'.
09:39:38.551 target.py         DEBUG  Target is a dockerfile.
09:39:38.552 ruleset.py        DEBUG  Loading ruleset from file './rulesets/redhat.json'.
09:39:38.552 ruleset.py        DEBUG  Found groups: [u'labels', u'dockerfile', u'best_practices'].
09:39:38.552 ruleset.py        DEBUG  Getting checks for group 'labels'.
09:39:38.552 ruleset.py        DEBUG  Loading check instance for name
09:39:38.552 loader.py         DEBUG  Getting check(s) from the file '/home/tt/g/user-cont/colin/colin/checks/labels/name.py'.
09:39:38.553 loader.py         DEBUG  Check instance 'name_label_required' found.
09:39:38.553 ruleset.py        DEBUG  Loading check instance for com_redhat_component
09:39:38.553 loader.py         DEBUG  Getting check(s) from the file '/home/tt/g/user-cont/colin/colin/checks/labels/com_redhat_component.py'.
09:39:38.553 loader.py         DEBUG  Check instance 'com_redhat_component_label_required' found.
09:39:38.553 ruleset.py        DEBUG  Loading check instance for summary
09:39:38.553 loader.py         DEBUG  Getting check(s) from the file '/home/tt/g/user-cont/colin/colin/checks/labels/summary.py'.
09:39:38.553 loader.py         DEBUG  Check instance 'summary_label_required' found.
09:39:38.553 ruleset.py        DEBUG  Loading check instance for version
09:39:38.553 loader.py         DEBUG  Getting check(s) from the file '/home/tt/g/user-cont/colin/colin/checks/labels/version.py'.
09:39:38.554 loader.py         DEBUG  Check instance 'version_label_required' found.
09:39:38.554 ruleset.py        DEBUG  Loading check instance for usage
09:39:38.554 loader.py         DEBUG  Getting check(s) from the file '/home/tt/g/user-cont/colin/colin/checks/labels/usage.py'.
09:39:38.554 loader.py         DEBUG  Check instance 'usage_label_required' found.
09:39:38.554 ruleset.py        DEBUG  Loading check instance for io_k8s_display-name
09:39:38.554 loader.py         DEBUG  Getting check(s) from the file '/home/tt/g/user-cont/colin/colin/checks/labels/io_k8s_display-name.py'.
09:39:38.554 loader.py         DEBUG  Check instance 'io_k8s_display-name_label_required' found.
09:39:38.554 ruleset.py        DEBUG  Loading check instance for io_openshift_tags
09:39:38.554 loader.py         DEBUG  Getting check(s) from the file '/home/tt/g/user-cont/colin/colin/checks/labels/io_openshift_tags.py'.
09:39:38.555 loader.py         DEBUG  Check instance 'io_openshift_tags_label_required' found.
09:39:38.555 ruleset.py        DEBUG  Loading check instance for description
09:39:38.555 loader.py         DEBUG  Getting check(s) from the file '/home/tt/g/user-cont/colin/colin/checks/labels/description.py'.
09:39:38.555 loader.py         DEBUG  Check instance 'description_label' found.
09:39:38.555 ruleset.py        DEBUG  Loading check instance for io_k8s_description
09:39:38.555 loader.py         DEBUG  Getting check(s) from the file '/home/tt/g/user-cont/colin/colin/checks/labels/io_k8s_description.py'.
09:39:38.555 loader.py         DEBUG  Check instance 'io.k8s.description_label' found.
09:39:38.556 ruleset.py        DEBUG  Loading check instance for architecture_capital_deprecated
09:39:38.556 loader.py         DEBUG  Getting check(s) from the file '/home/tt/g/user-cont/colin/colin/checks/labels/architecture_capital_deprecated.py'.
09:39:38.556 loader.py         DEBUG  Check instance 'architecture_label_capital_deprecated' found.
09:39:38.556 ruleset.py        DEBUG  Loading check instance for bzcomponent_deprecated
09:39:38.556 loader.py         DEBUG  Getting check(s) from the file '/home/tt/g/user-cont/colin/colin/checks/labels/bzcomponent_deprecated.py'.
09:39:38.556 loader.py         DEBUG  Check instance 'bzcomponent_deprecated' found.
09:39:38.556 ruleset.py        DEBUG  Loading check instance for name_capital_deprecated
09:39:38.556 loader.py         DEBUG  Getting check(s) from the file '/home/tt/g/user-cont/colin/colin/checks/labels/name_capital_deprecated.py'.
09:39:38.557 loader.py         DEBUG  Check instance 'name_label_capital_deprecated' found.
09:39:38.557 ruleset.py        DEBUG  Loading check instance for version_capital_deprecated
09:39:38.557 loader.py         DEBUG  Getting check(s) from the file '/home/tt/g/user-cont/colin/colin/checks/labels/version_capital_deprecated.py'.
09:39:38.557 loader.py         DEBUG  Check instance 'version_label_capital_deprecated' found.
09:39:38.557 ruleset.py        DEBUG  Loading check instance for install_capital_deprecated
09:39:38.557 loader.py         DEBUG  Getting check(s) from the file '/home/tt/g/user-cont/colin/colin/checks/labels/install_capital_deprecated.py'.
09:39:38.557 loader.py         DEBUG  Check instance 'install_label_capital_deprecated' found.
09:39:38.557 ruleset.py        DEBUG  Loading check instance for uninstall_capital_deprecated
09:39:38.557 loader.py         DEBUG  Getting check(s) from the file '/home/tt/g/user-cont/colin/colin/checks/labels/uninstall_capital_deprecated.py'.
09:39:38.558 loader.py         DEBUG  Check instance 'uninstall_label_capital_deprecated' found.
09:39:38.558 ruleset.py        DEBUG  Loading check instance for release_capital_deprecated
09:39:38.558 loader.py         DEBUG  Getting check(s) from the file '/home/tt/g/user-cont/colin/colin/checks/labels/release_capital_deprecated.py'.
09:39:38.558 loader.py         DEBUG  Check instance 'release_label_capital_deprecated' found.
09:39:38.558 ruleset.py        DEBUG  Check instance name_label_required added.
09:39:38.558 ruleset.py        DEBUG  Check instance com_redhat_component_label_required added.
09:39:38.558 ruleset.py        DEBUG  Check instance summary_label_required added.
09:39:38.558 ruleset.py        DEBUG  Check instance version_label_required added.
09:39:38.558 ruleset.py        DEBUG  Check instance usage_label_required added.
09:39:38.558 ruleset.py        DEBUG  Check instance io_k8s_display-name_label_required added.
09:39:38.558 ruleset.py        DEBUG  Check instance io_openshift_tags_label_required added.
09:39:38.558 ruleset.py        DEBUG  Check instance description_label added.
09:39:38.558 ruleset.py        DEBUG  Check instance io.k8s.description_label added.
09:39:38.558 ruleset.py        DEBUG  Check instance architecture_label_capital_deprecated added.
09:39:38.558 ruleset.py        DEBUG  Check instance bzcomponent_deprecated added.
09:39:38.559 ruleset.py        DEBUG  Check instance name_label_capital_deprecated added.
09:39:38.559 ruleset.py        DEBUG  Check instance version_label_capital_deprecated added.
09:39:38.559 ruleset.py        DEBUG  Check instance install_label_capital_deprecated added.
09:39:38.559 ruleset.py        DEBUG  Check instance uninstall_label_capital_deprecated added.
09:39:38.559 ruleset.py        DEBUG  Check instance release_label_capital_deprecated added.
09:39:38.559 ruleset.py        DEBUG  Loading check instance for vcs-url
09:39:38.559 loader.py         DEBUG  Getting check(s) from the file '/home/tt/g/user-cont/colin/colin/checks/labels/vcs-url.py'.
09:39:38.559 loader.py         DEBUG  Check instance 'vcs-url_label' found.
09:39:38.559 ruleset.py        DEBUG  Loading check instance for maintainer
09:39:38.559 loader.py         DEBUG  Getting check(s) from the file '/home/tt/g/user-cont/colin/colin/checks/labels/maintainer.py'.
09:39:38.559 loader.py         DEBUG  Check instance 'maintainer_label_required' found.
09:39:38.559 ruleset.py        DEBUG  Loading check instance for io_openshift_expose-services
09:39:38.560 loader.py         DEBUG  Getting check(s) from the file '/home/tt/g/user-cont/colin/colin/checks/labels/io_openshift_expose-services.py'.
09:39:38.560 loader.py         DEBUG  Check instance 'io.openshift.expose-services_label' found.
09:39:38.560 ruleset.py        DEBUG  Loading check instance for maintainer
09:39:38.560 loader.py         DEBUG  Getting check(s) from the file '/home/tt/g/user-cont/colin/colin/checks/labels/maintainer.py'.
09:39:38.560 loader.py         DEBUG  Check instance 'maintainer_label_required' found.
09:39:38.560 ruleset.py        DEBUG  Check instance vcs-url_label added.
09:39:38.560 ruleset.py        DEBUG  Check instance maintainer_label_required added.
09:39:38.560 ruleset.py        DEBUG  Check instance io.openshift.expose-services_label added.
09:39:38.560 ruleset.py        DEBUG  Check instance maintainer_label_required added.
09:39:38.560 ruleset.py        DEBUG  Getting checks for group 'dockerfile'.
09:39:38.560 ruleset.py        DEBUG  Loading check instance for maintainer_deprecated
09:39:38.560 loader.py         DEBUG  Getting check(s) from the file '/home/tt/g/user-cont/colin/colin/checks/dockerfile/maintainer_deprecated.py'.
09:39:38.561 loader.py         DEBUG  Check instance 'maintainer_deprecated' found.
09:39:38.561 ruleset.py        DEBUG  Loading check instance for from_tag
09:39:38.561 loader.py         DEBUG  Getting check(s) from the file '/home/tt/g/user-cont/colin/colin/checks/dockerfile/from_tag.py'.
09:39:38.561 loader.py         DEBUG  Check instance 'from_tag_not_latest' found.
09:39:38.561 ruleset.py        DEBUG  Check instance maintainer_deprecated added.
09:39:38.561 ruleset.py        DEBUG  Check instance from_tag_not_latest added.
09:39:38.561 ruleset.py        DEBUG  Getting checks for group 'best_practices'.
09:39:38.561 ruleset.py        DEBUG  Loading check instance for help_file
09:39:38.561 loader.py         DEBUG  Getting check(s) from the file '/home/tt/g/user-cont/colin/colin/checks/best_practices/help_file.py'.
09:39:38.562 loader.py         DEBUG  Check instance 'help_file_required' found.
09:39:38.562 ruleset.py        DEBUG  Loading check instance for cmd_or_entrypoint
09:39:38.562 loader.py         DEBUG  Getting check(s) from the file '/home/tt/g/user-cont/colin/colin/checks/best_practices/cmd_or_entrypoint.py'.
09:39:38.563 loader.py         DEBUG  Check instance 'cmd_or_entrypoint' found.
09:39:38.563 ruleset.py        DEBUG  Loading check instance for no_root
09:39:38.563 loader.py         DEBUG  Getting check(s) from the file '/home/tt/g/user-cont/colin/colin/checks/best_practices/no_root.py'.
09:39:38.564 loader.py         DEBUG  Check instance 'no_root' found.
09:39:38.564 ruleset.py        DEBUG  Check help_file_required not compatible with the target type: DOCKERFILE
09:39:38.564 ruleset.py        DEBUG  Check cmd_or_entrypoint not compatible with the target type: DOCKERFILE
09:39:38.564 ruleset.py        DEBUG  Check no_root not compatible with the target type: DOCKERFILE
09:39:38.564 check_runner.py   DEBUG  Going through checks.
09:39:38.564 check_runner.py   DEBUG  Checking group: labels
09:39:38.564 check_runner.py   DEBUG  Checking name_label_required
No handlers could be found for logger "__main__"
Traceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/tt/g/user-cont/colin/colin/cli/colin.py", line 200, in <module>
    cli()
  File "/home/tt/.local/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/home/tt/.local/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/home/tt/.local/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/tt/.local/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/tt/.local/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/tt/g/user-cont/colin/colin/cli/colin.py", line 76, in check
    _print_results(results=results, stat=stat)
  File "/home/tt/g/user-cont/colin/colin/cli/colin.py", line 153, in _print_results
    for r in check_results:
  File "colin/checks/result.py", line 150, in _result_generator
    for r in results:
  File "colin/core/check_runner.py", line 36, in _result_generator
    yield check.check(target)
  File "colin/checks/abstract/labels.py", line 36, in check
    labels=target.labels)
  File "colin/core/target.py", line 130, in labels
    return self.instance.labels
  File "/usr/lib/python2.7/site-packages/dockerfile_parse/parser.py", line 314, in labels
    return self._instruction_getter('LABEL', env_replace=self.env_replace)
  File "/usr/lib/python2.7/site-packages/dockerfile_parse/parser.py", line 344, in _instruction_getter
    for key, value in key_val_list:
TypeError: 'NoneType' object is not iterable
```

**Comment by lachmanfrantisek** [comment]
@TomasTomecek  It sounds like the bug in the  `dockerfile_parser`. Which version do you use?

**Comment by lachmanfrantisek** [comment]
@TomasTomecek  It's a problem with the label parsing in the dockerfile_parse.

It's funny, that @phracek use exactly the same Dockerfile in this issue:
https://github.com/DBuildService/dockerfile-parse/issues/28

I'm not sure if this was fixed in the new version but I will look at it.

(Since the fedora is 3 versions behind, the fix will not be here soon.)

**Comment by TomasTomecek** [comment]
I installed it from Fedora: `python2-dockerfile-parse-0.0.7-2.fc28.noarch`

**Comment by lachmanfrantisek** [comment]
This is a problem we have to fix on the parser side. If it is not fixed yet, I can look at it tomorrow. (Is there some real chance to make quicker releases of the parser?)

**Comment by jpopelka** [comment]
> Is there some real chance to make quicker releases of the parser?

If you mean upstream (PyPi), then [I'm still a maintainer](https://pypi.org/project/dockerfile-parse/).
If you mean downstream (Fedora), then @TomasTomecek  [should still have rights](https://src.fedoraproject.org/rpms/python-dockerfile-parse/)

**Comment by lachmanfrantisek** [comment]
@jpopelka  we're lucky to have such important people in the team..;-)

If I am not wrong, the fix is in the version >=0.0.9. (Also mentioned today [by Luiz here](https://github.com/DBuildService/dockerfile-parse/issues/28#issuecomment-382003155).)

1. @jpopelka Can you please release the new version to the PyPI?
2. @TomasTomecek  Can you please release the new version to the Fedora?

Thanks!!

**Comment by jpopelka** [comment]
> @jpopelka Can you please release the new version to the PyPI?

[done](https://pypi.org/project/dockerfile-parse/0.0.10/)

**Comment by lachmanfrantisek** [comment]
@jpopelka Thanks, it was quicker than I thought.

**Pull request merged**
