### PR TITLE
Rulesets in virtualenv

### PR DESCRIPTION
**Pull request by lachmanfrantisek**
- Allow loading rulesets from virtualenv.

### CODE REVIEW

**Comment by jpopelka** [comment]
[test]

**Comment by jpopelka** [comment]
LGTM, but `tests/unit/test_cli.py::test_check_command` keeps failing

**Comment by lachmanfrantisek** [comment]
> LGTM, but tests/unit/test_cli.py::test_check_command keeps failing

It seems like a change in the click package. It isn't related to this change -- I'll correct that in the next PR.

**Comment by lachmanfrantisek** [comment]
@jpopelka Thanks!

**Pull request merged**
