### PR TITLE
Make packit.yaml minimal

### PR DESCRIPTION
**Pull request by TomasTomecek**
So that it's not confusing to people.

### CODE REVIEW

**Comment by TomasTomecek** [comment]
Can we merge?

**Comment by lachmanfrantisek** [comment]
Is this really necessary?

I think we need to consider the jobs info soon.

**Comment by TomasTomecek** [comment]
> Is this really necessary?

Okay, imagine you add the complete config into your repo - you would expect that packit would pick up all the configuration and follow it, right? But nope, we don't have code to process it. So the user would be like: it's broken, it's not doing anything.

Let's make clear expectations

**Comment by lachmanfrantisek** [comment]
>  But nope, we don't have code to process it. 

I am just wondering if it is not easier to fix that instead of correcting all configs and documenting that.

**Comment by TomasTomecek** [comment]
eaiser to write a ton of code which will take days to merge and weeks to release? :D

you are brave

BTW all the docs for propose-update describes only config options which are implemented

**Pull request merged**
