### PR TITLE
Add packit config.

### PR DESCRIPTION
**Pull request by lachmanfrantisek**

### CODE REVIEW

**Comment by jpopelka** [comment]
Could it be YAML/TOML ?

- https://www.lucidchart.com/techblog/2018/07/16/why-json-isnt-a-good-configuration-language
- https://arp242.net/weblog/json_as_configuration_files-_please_dont
- https://revelry.co/json-configuration-file-format

**Comment by lachmanfrantisek** [comment]
> Could it be YAML/TOML ?

Yes, we are using [anymarkup](https://github.com/bkabrda/anymarkup) so it can be whatever `anymarkup` supports.. If it is not a big problem, I would leave it in JSON for know...

**Comment by lachmanfrantisek** [comment]
@jpopelka Thanks for the links...

**Comment by lachmanfrantisek** [comment]
> @lachmanfrantisek lachmanfrantisek force-pushed 

Sorry, I've forgotten to `git add` the missing comma.

**Comment by TomasTomecek** [comment]
> Could it be YAML/TOML ?

I prefer ROFL format.

**Comment by jpopelka** [comment]
> I prefer ROFL format.

I'd prefer:
- a smiley if that's a joke
- url/link if you're serious

**Comment by TomasTomecek** [comment]
Lol!

**Pull request merged**
