### PR TITLE
Change version also in the spec file

### PR DESCRIPTION
**Pull request by lachmanfrantisek**
Change version also in the spec file

Signed-off-by: lachmanfrantisek <flachman@redhat.com>

Please wait a bit. Not merge now!

### CODE REVIEW

**Comment by TomasTomecek** [comment]
It's also a good practice to write a changelog entry. There is a tool which can help with that: `rpmdev-bumpspec ./*.spec`; the issue is that it also updates `%release`

**Comment by lachmanfrantisek** [comment]
@TomasTomecek  You were quick. I've added that after your merge...

**Comment by TomasTomecek** [comment]
push that commit directly to master

**Comment by lachmanfrantisek** [comment]
@TomasTomecek  I don't like pushing to master -- I've made third pull-request..;-)

https://github.com/user-cont/colin/pull/102

**Pull request merged**
