### PR TITLE
Packit config update

### PR DESCRIPTION
**Pull request by lachmanfrantisek**
- Add smoke test for testing farm.
- Update jobs in packit config.

### CODE REVIEW

**Comment by lachmanfrantisek** [comment]
> Also `upstream_project_name` -> `upstream_package_name`

Thanks

**Comment by lachmanfrantisek** [comment]
@jpopelka PTAL

**Comment by jpopelka** [comment]
> @jpopelka PTAL

I already approved, feel free to merge.

**Pull request merged**
