### PR TITLE
Packaging and metadata fixes

### PR DESCRIPTION
**Pull request by lachmanfrantisek**
- Remove Python2 from setup.py.
    - Is there anything else that needs to be done in specfile?
- Allow metadata checks for podman images.
- Remove conu for now.
   - We can add it later with move to the conu-podman backend.

### CODE REVIEW

**Comment by lachmanfrantisek** [comment]
@TomasTomecek Thanks, I did not want to remove that test, but I can change the package.

**Comment by lachmanfrantisek** [comment]
@TomasTomecek done, thanks

**Comment by TomasTomecek** [comment]
there are a ton of test failures :<

**Comment by lachmanfrantisek** [comment]
Unused import fixed, but the ostree tests are failing... (Some breaking package update on centos-ci?)

**Comment by TomasTomecek** [comment]
> (Some breaking package update on centos-ci?)

That's easily possible since the ostree code is really fragile.

**Comment by TomasTomecek** [comment]
Let me know if you want to have this merged.

**Comment by TomasTomecek** [comment]
sounds good

**Comment by lachmanfrantisek** [comment]
Thanks! I'm going to release `0.3.1`.

**Pull request merged**
