### PR TITLE
Remove support for ostree format

### PR DESCRIPTION
**Pull request by lslebodn**
Fedora 30 was the latest one which had support for ostree format in
skopeo and the atomic utility is not available anymore on fedora 31

The oci format with the umoci utility is equivalent replacement
for unprivileged scanning with colin.

### CODE REVIEW

**Review by lachmanfrantisek — APPROVED** [review]
Thanks!

**Comment by lachmanfrantisek** [comment]
@lslebodn Do you want to make a new release once it is merged?

**Review by TomasTomecek — APPROVED** [review]
So long and thanks for all the fish!

**Comment by lslebodn** [comment]
> Do you want to make a new release once it is merged?

I think we can have new release :-)

**Pull request merged**
